import { useEffect, useContext } from "react";
import Head from "next/head";

import { DroneDeliveryContext } from "@/context/Context";

import clientPromise from "@/util/mongodb";
import Layout from "@/components/Layout";

export default function ThanksPage({ users }) {
  const { userData, handleChangeUser } = useContext(DroneDeliveryContext);
  useEffect(() => {
    // Clear out data in context
    handleChangeUser({});
  }, []);

  return (
    <Layout>
      <Head>
        <title>Thanks! - Drone Delivery</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className="flex flex-col items-center mt-10">
        <h1 className="text-3xl">Thanks for signing up!</h1>
      </div>
      <section className="mt-8 text-center">
        <h2 className="text-xl">Join our list of happy customers 😊</h2>

        <div className="relative w-full max-w-lg">
          <div className="absolute top-0 -left-14 w-72 h-72 bg-purple-300 rounded-full mix-blend-multiply filter blur-2xl opacity-50 animate-blob"></div>
          <div className="absolute top-0 -right-10 w-72 h-72 bg-yellow-300 rounded-full mix-blend-multiply filter blur-2xl opacity-50 animate-blob animation-delay-2000"></div>
          <div className="absolute -bottom-12 left-20 w-72 h-72 bg-pink-300 rounded-full mix-blend-multiply filter blur-2xl opacity-50 animate-blob animation-delay-4000"></div>
          <div className="relative bg-white border border-gray-100 shadow-md p-5 rounded-sm mt-5">
            {users.map((user) => {
              return <div key={user._id}>{user.name}</div>;
            })}
          </div>
        </div>
      </section>
    </Layout>
  );
}

export async function getServerSideProps(context) {
  const client = await clientPromise;
  const db = client.db("drone-delivery");
  const data = await db.collection("users").find({}).limit(20).toArray();
  const users = JSON.parse(JSON.stringify(data));

  return {
    props: { users: users },
  };
}
