import { useEffect, useContext } from "react";
import Head from "next/head";
import router, { useRouter } from "next/router";

import { DroneDeliveryContext } from "@/context/Context";

import Layout from "@/components/Layout";
import Button from "@/components/Button";

export default function VerifyPage() {
  const { userData, handleChangeUser } = useContext(DroneDeliveryContext);

  useEffect(() => {
    // If no user exists in context is empty, go back to home page
    // if (Object.keys(userData).length === 0 || userData.name === "") {
    //   router.push("/");
    // }
  }, []);

  async function createUser(user) {
    const data = await fetch(
      `http${process.env.NEXT_PUBLIC_URL}/api/createUser?name=${user.name}&street=${user.street}&city=${user.city}&state=${user.state}&zipcode=${user.zipcode}&lat=${user.geocode.lat}&lng=${user.geocode.lng}&verified=true`
    );
    const res = await data.json();
  }

  function verifiedSubmit(e) {
    e.preventDefault();

    // Put user data from context into db
    createUser(userData);
    // Redirect to the thanks page
    router.push("/thanks");
  }

  function unVerifiedSubmit(e) {
    e.preventDefault();
    router.push("/");
  }

  return (
    <Layout>
      <Head>
        <title>Drone Delivery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="relative w-full max-w-lg">
        <div className="absolute top-14 -left-14 w-72 h-72 bg-purple-300 rounded-full mix-blend-multiply filter blur-2xl opacity-50 animate-blob"></div>
        <div className="absolute top-20 -right-14 w-72 h-72 bg-yellow-300 rounded-full mix-blend-multiply filter blur-2xl opacity-50 animate-blob animation-delay-2000"></div>
        <div className="absolute -bottom-10 left-24 w-72 h-72 bg-pink-300 rounded-full mix-blend-multiply filter blur-2xl opacity-50 animate-blob animation-delay-4000"></div>
        <div className="mt-32 relative bg-white flex flex-col items-center border border-gray-100 shadow-md px-5 py-16 rounded-sm">
          <div>
            <p className="text-center">
              {userData.name} please verify that <br />
              <span className="border border-green-500 bg-green-100 text-green-800 rounded-md px-1">
                {userData.street}, {userData.city}, {userData.state}{" "}
                {userData.zipcode}
              </span>
              <br />
              is your correct address.
            </p>
          </div>
          <div className="flex gap-5">
            <Button handleSubmit={verifiedSubmit}>Verify</Button>
            <Button color="red" handleSubmit={unVerifiedSubmit}>
              This is Incorrect
            </Button>
          </div>
        </div>
      </div>
    </Layout>
  );
}
